Boost 1.67 compatibility
Note: this is a cherry-pick from gnuradio upstream,
  commit https://github.com/gnuradio/gnuradio/commit/86fa85feef81e69dd1354b393118459340b94489

On Travis CI, updating boost, yields a pretty new boost (1.67) which
breaks during build. This is on OS X builds using `brew`.

Error is:
```
~/scopy/deps/gnuradio/gr-blocks/lib/message_strobe_impl.cc:93:35: error: no matching conversion for functional-style cast from 'float' to 'boost::posix_time::milliseconds' (aka 'subsecond_duration<boost::posix_time::time_duration, 1000>')
        boost::this_thread::sleep(boost::posix_time::milliseconds(d_period_ms));
```

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>